"""Is_a_vet added to users

Revision ID: 114f8237346a
Revises: 55f56ca2ca08
Create Date: 2022-04-08 10:18:51.882076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114f8237346a'
down_revision = '55f56ca2ca08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_a_vet', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_a_vet')
    # ### end Alembic commands ###
