"""empty message

Revision ID: 6b6c15c2fc2b
Revises: bb5b79665223
Create Date: 2022-05-22 14:29:50.014870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6c15c2fc2b'
down_revision = 'bb5b79665223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('scratching_triggers_when_walking_on_a_leash', sa.Integer(), nullable=True))
    op.drop_column('submissions', 'other_signs_licking_limb_paw')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('other_signs_licking_limb_paw', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('submissions', 'scratching_triggers_when_walking_on_a_leash')
    # ### end Alembic commands ###
