"""empty message

Revision ID: 6ff5c5918758
Revises: 9df973e7ea1b
Create Date: 2022-04-21 03:26:20.740561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ff5c5918758'
down_revision = '9df973e7ea1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('downstairs', sa.String(length=256), nullable=False))
    op.drop_column('submissions', 'downstair')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('downstair', mysql.VARCHAR(length=256), nullable=False))
    op.drop_column('submissions', 'downstairs')
    # ### end Alembic commands ###
