"""empty message

Revision ID: 9df973e7ea1b
Revises: b106bf60624c
Create Date: 2022-04-21 03:23:57.668228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9df973e7ea1b'
down_revision = 'b106bf60624c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('upstairs', sa.String(length=256), nullable=False))
    op.add_column('submissions', sa.Column('downstair', sa.String(length=256), nullable=False))
    op.add_column('submissions', sa.Column('jumping', sa.String(length=256), nullable=False))
    op.alter_column('submissions', 'dogs_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('submissions', 'dogs_breed',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('submissions', 'dogs_sex',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('submissions', 'dogs_neutered',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.drop_column('submissions', 'stairs_jumping')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('stairs_jumping', mysql.VARCHAR(length=128), nullable=False))
    op.alter_column('submissions', 'dogs_neutered',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('submissions', 'dogs_sex',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('submissions', 'dogs_breed',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('submissions', 'dogs_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.drop_column('submissions', 'jumping')
    op.drop_column('submissions', 'downstair')
    op.drop_column('submissions', 'upstairs')
    # ### end Alembic commands ###
