"""added walking on leash

Revision ID: bb5b79665223
Revises: 24eec319a5dd
Create Date: 2022-05-22 08:43:09.515944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb5b79665223'
down_revision = '24eec319a5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('scratching_triggers_when_walking_on_a_leash', sa.Integer(), nullable=True))
    op.drop_column('submissions', 'other_signs_licking_limb_paw')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('other_signs_licking_limb_paw', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('submissions', 'scratching_triggers_when_walking_on_a_leash')
    # ### end Alembic commands ###
