"""empty message

Revision ID: ff185bd394f3
Revises: 6ff5c5918758
Create Date: 2022-04-21 04:01:23.612140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff185bd394f3'
down_revision = '6ff5c5918758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'scratching_site',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('submissions', 'scratching_triggers',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('submissions', 'vocalising_when_scratching',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('submissions', 'nibbling_licking',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('submissions', 'vocalisation_yelping_or_screaming',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('submissions', 'vocalisation_yelping_or_screaming_text_box',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('submissions', 'interactions',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('submissions', 'interactions_text_box',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('submissions', 'other_signs',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'other_signs',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('submissions', 'interactions_text_box',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('submissions', 'interactions',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('submissions', 'vocalisation_yelping_or_screaming_text_box',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('submissions', 'vocalisation_yelping_or_screaming',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('submissions', 'nibbling_licking',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('submissions', 'vocalising_when_scratching',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('submissions', 'scratching_triggers',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('submissions', 'scratching_site',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
